### ISSUE TITLE
[1.15.1] Crash from clicking Backpacked in Modlist

### ISSUE THREAD

**Issue by Boomflex** [MrCrayfish/Backpacked#3]
https://pastebin.com/Zr6in5jK

Basicly I clicked modlist button in the main menu, and then clicked backpacked mod button, game crashed.

https://github.com/Boomflex/JustNotEnoughMods/issues/9

**Comment by realTIMematrix** [comment]
Got same Issue, only Backpacked installed with latest forge

Hope additional Infos will help to fix this. 

[https://pastebin.com/djBuNvxa](https://pastebin.com/djBuNvxa)

Poste similar Issue for another mod and the modmaker fixes this with adding a logo file.

see also: [https://github.com/Nukeologist/MetaChests/issues/2](https://github.com/Nukeologist/MetaChests/issues/2)

**Comment by SuperHarmony910** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 23/07/20 5:38 PM
Description: mouseClicked event handler

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:428) ~[zipfs.jar:1.8.0_51] {}
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_51] {}
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_51] {}
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:66) ~[?:?] {re:classloading}
	at net.minecraft.resources.ResourcePack.func_195763_b(SourceFile:53) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.lambda$updateCache$12(ModListScreen.java:430) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen$$Lambda$3601/1469963860.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.updateCache(ModListScreen.java:421) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.setSelected(ModListScreen.java:406) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.gui.widget.ModListWidget$ModEntry.mouseClicked(ModListWidget.java:106) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.list.AbstractList.mouseClicked(AbstractList.java:289) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:sensitivity,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3577/1364803759.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:sensitivity,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:sensitivity,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3576/718150867.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:cgm:sensitivity,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$2981/2130054146.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:949) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:minecraft,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:controllable:minecraft,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/947173397.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:428)
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:66)
	at net.minecraft.resources.ResourcePack.func_195763_b(SourceFile:53)
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.lambda$updateCache$12(ModListScreen.java:430)
	at net.minecraftforge.fml.client.gui.screen.ModListScreen$$Lambda$3601/1469963860.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.updateCache(ModListScreen.java:421)
	at net.minecraftforge.fml.client.gui.screen.ModListScreen.setSelected(ModListScreen.java:406)
	at net.minecraftforge.fml.client.gui.widget.ModListWidget$ModEntry.mouseClicked(ModListWidget.java:106)
	at net.minecraft.client.gui.widget.list.AbstractList.mouseClicked(AbstractList.java:289)
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$3577/1364803759.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraftforge.fml.client.gui.screen.ModListScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$3576/718150867.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$2981/2130054146.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:123)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:949)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$422/947173397.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1108228768 bytes (1056 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		backpacked-1.4.1-mc1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		glasscutter-1.0.1-mc1.15.2.jar Glasscutter {glasscutter@1.0.1 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		improvedwolves-1.0.0-mc1.15.2.jar Improved Wolves {improvedwolves@1.0.0 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		cgm-0.16.1-mc1.15.2.jar MrCrayfish's Gun Mod {cgm@0.16.1 DONE}
		cfm-7.0.0-pre16-mc1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		venture-1.0.0-mc1.15.2.jar Venture {venture@1.0.0 DONE}
		vehicle-0.44.0-mc1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.0 DONE}
		goblintraders-1.2.0-mc1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		controllable-0.8.0-mc1.15.2.jar Controllable {controllable@0.8.0 DONE}
		goldenhopper-1.1.1-mc1.15.2.jar Golden Hopper {goldenhopper@1.1.1 DONE}
	Launched Version: 1.15.2-forge-31.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 25.20.100.6577, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (Australia)
	CPU: 4x Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz

**Comment by MrCrayfish** [comment]
Should be fixed now!
