### ISSUE TITLE
[1.16.5] Error when stopping server

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/Backpacked#46]
When stopping a server, a configuration error is shown which may cause the server to hang forever without actually stopping.

Here's the error from the log:  
```
[31Mar2021 15:50:11.463] [Server thread/ERROR] [net.minecraftforge.fml.config.ConfigFileTypeHandler/]: Failed to remove config ./world/serverconfig/backpacked-server.toml from tracker!
java.lang.NullPointerException: null
	at com.electronwill.nightconfig.core.file.FileWatcher.removeWatch(FileWatcher.java:134) ~[core-3.6.2.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.unload(ConfigFileTypeHandler.java:76) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:114) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$unloadConfigs$2(ConfigTracker.java:88) ~[forge:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:88) ~[forge:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:135) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:682) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by MrCrayfish** [comment]
I'll look into it. Definitely a strange error as the config system is handled by Forge, not my mod. Is there any additional information before the error? See the debug log file.

**Comment by MarioSMB** [comment]
I've been debugging it for the past few hours, and tracked down the source of the error to another mod: Performant. Its config was rewritten in a recent update and it wasn't correctly handling an outdated config.  
Apologies for the false positive here, I'll be reporting it on their tracker.
