### ISSUE TITLE
Mohist crashes with Backpacked

### ISSUE THREAD

**Issue by Redacted00** [MrCrayfish/Backpacked#72]
When I put the mod on a server with the Mohist core then it crashes
(Version: 2.0.4)

```
Exception in thread "main" [21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:128)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:125)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraftforge.server.ServerMain.main(ServerMain.java:109)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:05:43 INFO]: [java.lang.ThreadGroup:uncaughtException:-1]:  ... 7 more
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:34)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.util.registry.WorldGenRegistries.lambda$static$8(WorldGenRegistries.java:90)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at java.base/java.util.LinkedHashMap.forEach(Unknown Source)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:89)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.util.registry.Registry.<clinit>(Registry.java:465)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:41)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at net.minecraft.server.Main.main(Main.java:141)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      ... 13 more
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method beforeCollect(Lnet/minecraft/block/BlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Hand;Lnet/minecraft/util/math/BlockRayTraceResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in backpacked.mixins.json:common.ComposterBlockMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap backpacked.refmap.json
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[21:05:43 INFO]: [java.lang.Throwable:printStackTrace:-1]:      ... 32 more
```

[Debug](https://pastebin.com/zB3uZftv)
[Latest](https://pastebin.com/SHqmSk93)

**Comment by Redacted00** [comment]
New crash on version 2.1.0

https://pastebin.com/3K2t4n6e - Debug
https://pastebin.com/9jLaUdVm - Lastest

**Comment by MrCrayfish** [comment]
Should be fixed in https://github.com/MrCrayfish/Backpacked/commit/3032ceabec38e9b34a657733fc25154700266a4b
