### ISSUE TITLE
ClassNotFoundException for Model class in 2.1.1

### ISSUE THREAD

**Issue by VadamDev** [MrCrayfish/Backpacked#80]
Hello, I got a ClassNotFoundException for net.minecraft.client.renderer.model.Model by backpacked, I'm on the 36.2.29 forge version.

at com.mrcrayfish.backpacked.common.BackpackManager.register(BackpackManager.java:56) ~[backpacked:2.1.1]
at com.mrcrayfish.backpacked.common.BackpackManager.<init>(BackpackManager.java:38) ~[backpacked:2.1.1]
at com.mrcrayfish.backpacked.common.BackpackManager.instance(BackpackManager.java:29) ~[backpacked:2.1.1]
at com.mrcrayfish.backpacked.common.UnlockTracker.<init>(UnlockTracker.java:55) ~[backpacked:2.1.1]
at com.mrcrayfish.backpacked.common.UnlockTracker.<init>(UnlockTracker.java:42) ~[backpacked:2.1.1]
at com.mrcrayfish.backpacked.common.UnlockTracker$Provider.<init>(UnlockTracker.java:240) ~[backpacked:2.1.1]
at com.mrcrayfish.backpacked.common.UnlockTracker.attachCapabilities(UnlockTracker.java:121) ~[backpacked:2.1.1]

**Comment by wolfkidsounds** [comment]
Having the same problem right now (server side) - how did you fix the issue?

**Comment by MrCrayfish** [comment]
Yes but release is not out.
