### ISSUE TITLE
Registry Object not present: backpacked:imbued_hide. can't join my server after grabbing a death totem from a different mod.

### ISSUE THREAD

**Issue by Galygious** [MrCrayfish/Backpacked#85]
Assume its an inventory issue. Crash report below.
Death Totem is from maessentials.
when I grabbed the totem to pick my body back up I was kicked. then the client instantly crashes every time I attempt to join. no issues with the server. other players still online. not sure about the chunk being loaded or not. don't want to send anyone to get stuck too.
server's forge version is below
[main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.55, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, nogui]

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/11/22, 4:01 PM
Description: Unexpected error

java.lang.NullPointerException: Registry Object not present: backpacked:imbued_hide
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:116) ~[forge-1.18.1-39.0.55-universal.jar%23112!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.item.ItemEntity.handler$zzh000$fireImmuneHead(ItemEntity.java:526) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:backpacked.mixins.json:common.ItemEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.item.ItemEntity.m_5825_(ItemEntity.java) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:backpacked.mixins.json:common.ItemEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6060_(Entity.java:1935) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:backpacked.mixins.json:common.EntityMixin,pl:mixin:APP:iceberg.mixins.json:EntityMixin,pl:mixin:APP:improvedmobs.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRenderer.m_6086_(EntityRenderer.java:43) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderer.m_114505_(EntityRenderer.java:35) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114394_(EntityRenderDispatcher.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1434) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1230) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1056) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:831) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.55.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:116) ~[forge-1.18.1-39.0.55-universal.jar%23112!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.item.ItemEntity.handler$zzh000$fireImmuneHead(ItemEntity.java:526) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:backpacked.mixins.json:common.ItemEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.item.ItemEntity.m_5825_(ItemEntity.java) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,re:classloading,pl:mixin:APP:backpacked.mixins.json:common.ItemEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6060_(Entity.java:1935) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:backpacked.mixins.json:common.EntityMixin,pl:mixin:APP:iceberg.mixins.json:EntityMixin,pl:mixin:APP:improvedmobs.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.EntityRenderer.m_6086_(EntityRenderer.java:43) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderer.m_114505_(EntityRenderer.java:35) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114394_(EntityRenderDispatcher.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1434) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1230) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1056) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Galygious'/112583, l='ClientLevel', x=1961.57, y=78.00, z=6412.78]]
	Chunk stats: 1521, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,96,0), Section: (at 0,0,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 8913189 game time, 9128170 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:APP:terrablender.mixins.json:client.MixinClientLevel,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.55.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, ilikewood-1.18.1-7.4.4.0.jar:ilikewood_resources, ilikewoodxbyg-1.18.1-7.4.1.jar:ilikewood_resources, ilikewoodxbiomesoplenty-1.18.1-7.4.0.jar:ilikewood_resources, quark-emote-pack, VisibleOres2.4.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3777424000 bytes (3602 MiB) / 5670699008 bytes (5408 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 50088.13
	Virtual memory used (MB): 28405.85
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 498.70
	JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17120m -Xms256m -XX:+UseG1GC -Xmx6G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: forge-39.0.55
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, ilikewood:ilikewood, ilikewood:byg, ilikewood:biomesoplenty, quark:emote_resources (incompatible), file/VisibleOres2.4.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		tetra-1.18.1-4.7.0.jar                            |Tetra                         |tetra                         |4.7.0               |DONE      |Manifest: NOSIGNATURE
		Amplified Nether 1.0.1 ~ Forge.jar                |Amplified Nether + Seed Fix   |seedfix                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		TreeChop-1.18.1-0.15.6.jar                        |HT's TreeChop                 |treechop                      |0.15.6              |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.4.1.112.jar                          |Just Enough Items             |jei                           |9.4.1.112           |DONE      |Manifest: NOSIGNATURE
		Neat 1.8-30.jar                                   |Neat                          |neat                          |1.8-30              |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.20.3.1_Forge_1.18.jar            |Xaero's World Map             |xaeroworldmap                 |1.20.3.1            |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0+15.jar               |Controlling                   |controlling                   |9.0+15              |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.10-1.18.jar                          |Citadel                       |citadel                       |1.10.10             |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.17.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.1-Forge-24.jar                      |YUNG's API                    |yungsapi                      |1.18.1-Forge-24     |DONE      |Manifest: NOSIGNATURE
		chromatocreeper-1.18.1-1.1.jar                    |§3Chromato Creeper§r          |chromatocreeper               |1.1                 |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.18.1-3.0.0.4.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.4             |DONE      |Manifest: NOSIGNATURE
		maessentials-1.18-3.7.1.jar                       |MaEssentials                  |maessentials                  |1.18-3.7.1          |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.1-1.17.0.7.jar                       |Carry On                      |carryon                       |1.17.0.7            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.14.0.155.jar         |Just Enough Resources         |jeresources                   |0.14.0.155          |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.1-9.0.80.jar              |CraftTweaker                  |crafttweaker                  |9.0.80              |DONE      |Manifest: NOSIGNATURE
		ilikewoodxbiomesoplenty-1.18.1-7.4.0.jar          |I Like Wood - Biomes o' Plenty|ilikewoodxbiomesoplenty       |1.18.1-7.4.0        |DONE      |Manifest: NOSIGNATURE
		signtools-forge.1.18-1.0.1.jar                    |Sign Tools                    |signtools                     |1.0.1               |DONE      |Manifest: NOSIGNATURE
		upgradednetherite-1.18.1-4.0.0.1-release.jar      |Upgraded Netherite            |upgradednetherite             |1.18.1-4.0.0.1-relea|DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tenshilib-1.18.1-1.4.0-forge.jar                  |TenshiLib                     |tenshilib                     |1.18.1-1.4.0        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.73.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.73     |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.1-1.8.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.1-1.8.0        |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.1-15.0.0.104-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.104   |DONE      |Manifest: NOSIGNATURE
		Jade-1.18-4.1.2.jar                               |Jade                          |jade                          |4.1.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.55-universal.jar                |Forge                         |forge                         |39.0.55             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		CreativeCore_v2.5.0_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.5.0               |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.18-1.3.jar                        |betterfpsdist mod             |betterfpsdist                 |1.18-1.3            |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.1-1.0.40.jar                         |Iceberg                       |iceberg                       |1.0.40              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.1-4.4.0.jar                            |mutil                         |mutil                         |4.4.0               |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.18.1-1.2.4.jar                |Legendary Tooltips            |legendarytooltips             |1.2.4               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.3.0_Forge_1.18.jar              |Xaero's Minimap               |xaerominimap                  |22.3.0              |DONE      |Manifest: NOSIGNATURE
		TreePlant-1.18.1-0.3.0.jar                        |HT's TreePlant                |treeplant                     |0.3.0               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.1-340.jar                                 |Quark                         |quark                         |3.1-340             |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.10.160.jar                        |OreExcavation                 |oreexcavation                 |1.10.160            |DONE      |Manifest: NOSIGNATURE
		WorldPreGenerator-1.18.1-2.0.1.jar                |World Pre Generator           |world_pre_generator           |2.0.1               |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18-1.6.0.jar            |Better Third Person           |betterthirdperson             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.1-1.18.1.jar                       |Backpacked                    |backpacked                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		IKnowWhatImDoing-5.0.0-forge.jar                  |I Know What I'm Doing         |iknowwhatimdoing              |5.0.0               |DONE      |Manifest: 42:2c:5e:4c:e2:f5:d1:07:7f:aa:29:ae:31:88:80:0c:b1:a6:87:6b:6a:2d:0f:67:57:e4:5a:4a:26:73:31:ac
		BetterStrongholds-Forge-1.18.1-1.0.2.jar          |YUNG's Better Strongholds     |betterstrongholds             |1.18.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		upgradedcore-1.18.1-3.0.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.18.1-3.0.0.0-relea|DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.3.0.jar                  |AppleSkin                     |appleskin                     |2.3.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		moreoverlays-1.20.5-mc1.18.1.jar                  |More Overlays Updated         |moreoverlays                  |1.20.5-mc1.18.1     |DONE      |Manifest: NOSIGNATURE
		Oh The Biomes You'll Go-forge-1.18.1-1.3.5.10.jar |Oh The Biomes You'll Go       |byg                           |1.3.5.10            |DONE      |Manifest: NOSIGNATURE
		ilikewood-1.18.1-7.4.4.0.jar                      |I Like Wood                   |ilikewood                     |1.18.1-7.4.4.0      |DONE      |Manifest: NOSIGNATURE
		Nullscape_v1.1_Fabric+Forge.jar                   |Seed Fix + Nullscape          |nullscape_forge               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		ilikewoodxbyg-1.18.1-7.4.1.jar                    |I Like Wood - Oh The Biomes Yo|ilikewoodxbyg                 |1.18.1-7.4.1        |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.18.1-1.8.1-forge.jar               |Improved Mobs Mod             |improvedmobs                  |1.18.1-1.8.1        |DONE      |Manifest: NOSIGNATURE
		PlayerRevive_v2.0.0-pre08_mc1.18.1.jar            |PlayerRevive                  |playerrevive                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11              |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-1.18.1-0.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |0.3.0               |DONE      |Manifest: NOSIGNATURE
		createaddition-1.18.1-20220125a.jar               |Create Crafts & Additions     |createaddition                |1.18.1-20220125a    |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 3fc2d8b4-d18f-47cd-a4a7-634c968097d8
	FML: 39.0
	Forge: net.minecraftforge:39.0.55
```

**Comment by Galygious** [comment]
Server and client version missmatched. got it fixed!
